### ISSUE TITLE
file absence

### ISSUE THREAD

**Issue by MrYu001** [PSI-Intention2022/PSI-Intention#1]
wow! how a amazing work you done!
I encounter a little trouble when i try to use this datasets in pedestrian intention prediction task, when i pre-process the data, i did not find the cv_annotation, nlp_annotaion and frames.xml mentioned in the pedestrian_intention_database_processing.py, so i hope the author can help me to solve this problem at your convenience! thank you!

**Comment by scottjingtt** [comment]
Hi Mr. Yu, 
If you follow the steps provided pre-process the data, after run ''python reorganize_annotations.py'', the cv_annotation and nlp_annotation will be created automatically. I have double checked this should work. Please let me know if this answer addressed your question. Thanks

**Comment by MrYu001** [comment]
Follow your advice, i read the "python reorganize_annotations.py" again, the created "cv_annotation" and "nlp_annotation" are just two file folder and not file. Furthermore, when i run the "python reorganize_annotations.py",  it will rise a run error that indicated me "can not find frame file", and i check the datasets to find frame file in "Dataset", but i can not find it.

**Comment by scottjingtt** [comment]
Hi Mr. Yu, I am sorry but I am not sure what's the issue you are facing. The "cv_annotations" and "nlp_annotations" are the two folders containing all labels. If you cannot run the "reorganize_annotations.py" file, you probably haven't finished the processing so those annotations files are not created successfully yet. Please make sure you follow all prior steps (maybe modify the paths in the scripts in case there is any unexpected mismatch on your machine). Make sure you can run the "reorganize_annotations.py" file successfully first.
Besides, back to your first question, I didn't see any file names as "frames.xml" required in the "pedestrian_intention_database_processing.py". So please double check again and we can discuss later. 
Thanks

**Comment by MrYu001** [comment]
“frames_path = 'G:/IUPUI数据集/Dataset/frames'” this is the related code in "reorganize_annotations.py" at line 9.

**Comment by scottjingtt** [comment]
Yes, if you follow prior steps and run "python split_clips_to_frames.py", you will have the raw videos split into frames and stored in this path.

**Comment by MrYu001** [comment]
I'm so sorry, its my fault, after run the "split_clips_to_frames.py", all the problem has been solved. thank you!
